openapi: 3.0.3
info:
  title: TaskManager log models
  description: Log models for logging services of taskManager
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: {}

components:
  schemas:
    CommonLogModel:
      title: Общая модель лога
      description: Общая модель лога для всех микросервисов системы
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        task:
          $ref: '#/components/schemas/MgrLogModel'
        #        comments:
        #          $ref: '#/components/schemas/MgrLogModel'
        #        files:
        #          $ref: '#/components/schemas/MgrLogModel'
        #        images:
        #          $ref: '#/components/schemas/MgrLogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    # переименовать в MgrTaskLogModel
    MgrLogModel:
      title: Модель лога для микросервиса TaskManager
      type: object
      properties:
        requestId:
          type: string
        operation:
          $ref: '#/components/schemas/MgrLogOperation'
        requestTask:
          $ref: '#/components/schemas/TaskLog'
        requestFilter:
          $ref: '#/components/schemas/TaskFilterLog'
        responseTask:
          $ref: '#/components/schemas/TaskLog'
        responseTasks:
          type: array
          items:
            $ref: '#/components/schemas/TaskLog'

    MgrLogOperation:
      type: string
      enum:
        - create
        - read
        - update
        - delete
        - search
        - init
        - finish

    ErrorLogModel:
      title: Модель лога для ошибки
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string

    TaskLog:
      title: Модель лога для задачи
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        dtCreate:
          type: string
        deadline:
          type: string
        userId:
          type: string
        category:
          type: string
        status:
          type: string
        permissions:
          type: array
          uniqueItems: true
          items:
            type: string

    TaskFilterLog:
      title: Модель лога фильтра
      properties:
        searchString:
          type: string
        userId:
          type: string
        status:
          type: string
        deadline:
          type: string
        dtCreate:
          type: string

